stages:                                                                     
  - static                                                                  
                                                                            
static:                                                                     
  stage: static                                                             
  image: python:3.10-alpine                                                 
  before_script:                                                            
    - pip install -r sqa-requirements.txt                                   
    - apk update && apk add shellcheck                                      
  script:                                                                   
    - pylama .                                                              
    - djlint .                                                              
    - pip-audit                                                             
    - yamllint *.yml                                                        
    - shellcheck *.sh  