stages:                                                                     
  7   - static                                                                  
  6                                                                             
  5 static:                                                                     
  4   stage: static                                                             
  3   image: python:3.10-alpine                                                 
  2   before_script:                                                            
  1     - pip install -r sqa-requirements.txt                                   
9       - apk update && apk add shellcheck                                      
  1   script:                                                                   
  2     - pylama .                                                              
  3     - djlint .                                                              
  4     - pip-audit                                                             
  5     - yamllint *.yml                                                        
  6     - shellcheck *.sh  