version: '3'  #ren informativ, bruges ikke til noget rigtigt                
                                                                       
services:                                                                   
                                                                            
  nginx:  # snakker direkte ud mod internet, kan håndtere certifikater          (caching)                                                                   
    image: nginx:latest                                                      
    ports:                                                                   
      - 8000:80                                                              
                                                                            
  db:                                                                       
    image: postgres:13-alpine                                               
    volumes:                                                                
      - postgres_data:/var/lib/postgresql/data/                             
      - ./dbscripts/:/dbscripts/                                            
    env_file:                                                               
      - env                                                                 
                                                                             
  app:                                                                      
    image: coffee_shop:latest                                               
    volumes:                                                                
      - .:/app/                                                             
    env_file:                                                               
      - env                                                                 
    ports:                                                                  
      - 4000:8000                                                           
    depends_on:                                                             
      - db                                                                  
                                                                             
volumes:                                                                    
  postgres_data:                                                            
                   